### ISSUE TITLE
Ventura Release blocking

### ISSUE THREAD

**Issue by bwdiehl** [Theile/venturablocker#1]
Hello,
I was wondering will this proactively block ventura going forward. I saw the most recent update but did not know if that meant it will continue to block ventura even after the full release has come out.

**Comment by Theile** [comment]
This will block the "Install macOS Ventura" app, that is used to install Ventura. If Ventura is already running on the Mac, I don't see the need for this software, but if it's installed it would block it on that as well.

This software is a simple process that will simply detect if the other process with a specific bundle identifier is running, and then quit that. It will quit the beta, and hopefully also the full release (when released). If Apple continues the current name conventions.
