### ISSUE TITLE
Issue finalizing installation via MDM

### ISSUE THREAD

**Issue by torbentd** [Theile/venturablocker#4]
Hi there,

we are using Miradore MDM to deploy the venturablocker to our devices.
Unfortunately we have issues finishing the installation.

What works: 
- installation of venturablocker (almost)
- blocking ventura installer

What does not work:

- Our MDM is not receiving the correct info, that the app is installed properly
(miradore states "in progress" although it was installed and works)
Miradores Guide regarding this issue: https://www.miradore.com/knowledge/macos/troubleshooting-macos-app-deployments/

Our guess is either something is wrong with the bundle identifier or the version

As we are running out of ideas we hope to get some insight through this ticket.

Is this the correct identifier? dk.envo-it.venturablocker
And what version number is it? Package Info states: version="20221004"
But when using these 2 values we still get the "in progress" issues which is related to the fact, that the mdm server is not finding the proper receipt.
Our MDM sees the app but is unable to link the app in the inventory with the enrollment task of the app.'

Maybe you have some insights, where and how to fix that issue.

Thanks

**Comment by Theile** [comment]
You will not gain much from venturablocker at all. 

Apple is releasing ventura as an update, and not as a stand alone installer, so it will not really prevent your users from upgrading. 

I don't know Miradore MDM so cannot really help with that. I know the pkg is signed and notarized as it should be, so it can be distributed with Apple MDM commmands if prefered. But I don't know how Miradora is distributing pkgs.
